export const FETCHING_USER = 'FETCHING_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const LOG_OUT = 'LOG_OUT';
export const CLEAR_USERDATA = 'CLEAR_USERDATA';
export const LOG_USER_FAILURE = 'LOG_USER_FAILURE';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOGGING_USER = 'LOGGING_USER';
export const API_URL = 'http://192.168.68.114:3000/';

